In [2]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [3]:
df = pd.read_csv('Social_Network_Ads.csv')
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
pd.get_dummies(df).head()

User ID  Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0  15624510   19            19000          0              0            1
1  15810944   35            20000          0              0            1
2  15668575   26            43000          0              1            0
3  15603246   27            57000          0              1            0
4  15804002   19            76000          0              0            1

In [5]:
pd.get_dummies(df, columns=['Gender']).head()

User ID  Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0  15624510   19            19000          0              0            1
1  15810944   35            20000          0              0            1
2  15668575   26            43000          0              1            0
3  15603246   27            57000          0              1            0
4  15804002   19            76000          0              0            1

In [6]:
df=pd.get_dummies(df, drop_first=True, columns=['Gender'])

In [7]:
X = df.loc[:, ['Age', 'EstimatedSalary']].values
y = df['Purchased'].values


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size = 0.4, 
                                                    random_state = 0)

In [9]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)

In [10]:
meanX = sc_X.mean_
varX = sc_X.var_

In [11]:
meanX

array([3.77208333e+01, 6.79625000e+04])

In [12]:
varX

array([1.03851233e+02, 1.16696943e+09])

In [13]:
X_train

array([[-2.66990686e-01, -2.03814684e-01],
       [-1.64078656e+00,  1.09774515e-03],
       [-9.53888624e-01, -7.01459153e-01],
       [ 3.21778974e-01,  5.57288623e-01],
       [-7.07341328e-02, -1.02346440e+00],
       [-1.05201690e+00,  6.45108235e-01],
       [ 1.25522421e-01, -7.60005562e-01],
       [-9.53888624e-01,  1.61112397e+00],
       [-6.59503793e-01,  1.46475795e+00],
       [-1.24827345e+00,  5.57288623e-01],
       [-2.66990686e-01,  8.89173575e-02],
       [-7.07341328e-02,  5.96441534e-02],
       [-2.66990686e-01, -8.47825174e-01],
       [ 9.10548635e-01, -1.31619644e+00],
       [-2.66990686e-01,  2.31368087e+00],
       [ 1.00867691e+00,  2.05022203e+00],
       [-1.15014518e+00,  5.28015419e-01],
       [-1.24827345e+00,  3.23102990e-01],
       [ 1.40119002e+00,  2.05022203e+00],
       [ 1.30306174e+00, -1.31619644e+00],
       [-2.66990686e-01, -2.33087888e-01],
       [-4.63247240e-01,  1.31839193e+00],
       [-7.57632070e-01,  1.14275271e+00],
       [ 1.

In [14]:
X_test = sc_X.transform(X_test)
X_test

array([[-7.57632070e-01,  5.57288623e-01],
       [ 2.73941439e-02, -5.25819929e-01],
       [-2.66990686e-01,  2.06010174e-01],
       [-7.57632070e-01,  3.23102990e-01],
       [-2.66990686e-01, -5.25819929e-01],
       [-1.05201690e+00, -1.40401605e+00],
       [-6.59503793e-01, -1.55038207e+00],
       [-1.68862410e-01,  2.22586126e+00],
       [-1.93517139e+00,  1.09774515e-03],
       [ 9.10548635e-01, -7.30732357e-01],
       [-7.57632070e-01, -5.55093133e-01],
       [-9.53888624e-01, -3.79453908e-01],
       [-7.07341328e-02, -3.79453908e-01],
       [ 1.25522421e-01,  2.64556582e-01],
       [-1.73891484e+00,  5.28015419e-01],
       [-5.61375517e-01,  1.43548475e+00],
       [-7.07341328e-02,  2.64556582e-01],
       [-1.83704311e+00,  4.98742215e-01],
       [ 1.69557485e+00,  1.81603640e+00],
       [-2.66990686e-01, -1.34546964e+00],
       [-2.66990686e-01, -6.13639541e-01],
       [ 9.10548635e-01,  2.22586126e+00],
       [ 3.21778974e-01, -4.96546725e-01],
       [ 9.

In [15]:
from sklearn.linear_model import LogisticRegression
lr =LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [16]:
y_pred_lr=lr.predict(X_test)

In [17]:
from sklearn.tree import DecisionTreeClassifier
dtc =DecisionTreeClassifier()
dtc.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [18]:
y_pred_dtc=dtc.predict(X_test)

In [19]:
from sklearn.ensemble import RandomForestClassifier
rfc =RandomForestClassifier()
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [20]:
y_pred_rfc=rfc.predict(X_test)

In [21]:
from sklearn.svm import SVC
svc =SVC()
svc.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [22]:
y_pred_svc=svc.predict(X_test)
y_pred_svc

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1], dtype=int64)

In [23]:
from sklearn.metrics import confusion_matrix

In [24]:
cm= confusion_matrix(y_test,y_pred_lr)
cm


array([[93,  8],
       [15, 44]], dtype=int64)

In [25]:
from sklearn.metrics import accuracy_score,f1_score,precision_score,recall_score

# LR

In [26]:
acc_sc=accuracy_score(y_test,y_pred_lr)
acc_sc

0.85625

In [27]:
f1_sc=f1_score(y_test,y_pred_lr)
f1_sc

0.7927927927927929

In [28]:
p_sc=precision_score(y_test,y_pred_lr)
p_sc

0.8461538461538461

In [29]:
r_sc=recall_score(y_test,y_pred_lr)
r_sc

0.7457627118644068

# SVC

In [30]:
acc_sc1=accuracy_score(y_test,y_pred_svc)
acc_sc1

0.90625

In [31]:
f1_sc1=f1_score(y_test,y_pred_svc)
f1_sc1

0.8760330578512397

In [32]:
p_sc1=precision_score(y_test,y_pred_svc)
p_sc1

0.8548387096774194

In [33]:
r_sc1=recall_score(y_test,y_pred_svc)
r_sc1

0.8983050847457628

# DTC

In [34]:
acc_sc2=accuracy_score(y_test,y_pred_dtc)
acc_sc2

0.88125

In [35]:
f1_sc2=f1_score(y_test,y_pred_dtc)
f1_sc2

0.8256880733944953

In [36]:
p_sc2=precision_score(y_test,y_pred_dtc)
p_sc2

0.9

In [37]:
r_sc2=recall_score(y_test,y_pred_dtc)
r_sc2

0.7627118644067796

# RFC

In [38]:
acc_sc3=accuracy_score(y_test,y_pred_rfc)
acc_sc3

0.9125

In [39]:
f1_sc3=f1_score(y_test,y_pred_rfc)
f1_sc3

0.8771929824561402

In [40]:
p_sc3=precision_score(y_test,y_pred_rfc)
p_sc3

0.9090909090909091

In [42]:
r_sc3=recall_score(y_test,y_pred_rfc)
r_sc3

0.847457627118644

# Average Ensemble

In [46]:
from sklearn.ensemble import VotingClassifier
vc = VotingClassifier(estimators=[('Logistic Regression',lr),
                                 ('SVM',svc),
                                 ('Decision Tree',dtc),
                                 ('Random Forest',rfc)],
                                 voting='hard')
vc.fit(X_train,y_train)

VotingClassifier(estimators=[('Logistic Regression', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False))...obs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False))],
         flatten_transform=None, n_jobs=None, voting='hard', weights=None)